### PR TITLE
Delete Filters

### LINKED ISSUE #110: Remove filters from the codebase
- Delete the src/Filter/ directory
- Delete src/Query/Filered.php
- Delete the tests/Filter directory
- Delete tests/Query/FilteredTest.php
- Fix any test using the filtered query

### PR DESCRIPTION
**Pull request by TomChaton**
- Resolves #110
- Removed src/Filter/
- Removed tests/Filter/
- Removed src/Query/Filtered
- Removed src/Query/Lib/Filtered/
- Removed tests/Query/Filtered
- Uniquid not used in tests as it is not always serializable

### CODE REVIEW

**Comment by carlcasbolt** [comment]
This drop in coverage is upsetting but it's more important that we get rid of the 1.x logic.

**Comment by TomChaton** [comment]
I've modified the threshold, as it was unduly harsh, and impossible when deleting code on such a small codebase.
I'll review it periodically. Happy for this to go in?

**Comment by carlcasbolt** [comment]
Yep. Merging.

**Comment by carlcasbolt** [comment]
Merge not possible because of the failure above... :(

**Comment by TomChaton** [comment]
:muscle:

**Comment by TomChaton** [comment]
I knew I'd put that in for a reason. I'll amend the commit and then repush, that should do it.

**Comment by TomChaton** [comment]
@carlcasbolt This should merge now

**Pull request merged**
